apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment-example
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: webtestapp
    spec:
      volumes:
      - name: host-mount
        hostPath:
          path: /web_mount
      containers:
      - name: webtestcontainer
        image: webtestimage
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          readOnly: true
          name: host-mount
